// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Rasio Keuangan API
//
//  This file is auto-generated using go-swagger annotations.
//  Schemes:
//    http
//  Host: localhost:8082
//  BasePath: /
//  Version: 1.0.0
//  Contact: Your Name<your@email.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
