// Code generated by go-swagger; DO NOT EDIT.

package index_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetDirectV1SahamDpIxOKCode is the HTTP code returned for type GetDirectV1SahamDpIxOK
const GetDirectV1SahamDpIxOKCode int = 200

/*GetDirectV1SahamDpIxOK Successful response

swagger:response getDirectV1SahamDpIxOK
*/
type GetDirectV1SahamDpIxOK struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewGetDirectV1SahamDpIxOK creates GetDirectV1SahamDpIxOK with default headers values
func NewGetDirectV1SahamDpIxOK() *GetDirectV1SahamDpIxOK {

	return &GetDirectV1SahamDpIxOK{}
}

// WithPayload adds the payload to the get direct v1 saham dp ix o k response
func (o *GetDirectV1SahamDpIxOK) WithPayload(payload interface{}) *GetDirectV1SahamDpIxOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get direct v1 saham dp ix o k response
func (o *GetDirectV1SahamDpIxOK) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDirectV1SahamDpIxOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetDirectV1SahamDpIxBadRequestCode is the HTTP code returned for type GetDirectV1SahamDpIxBadRequest
const GetDirectV1SahamDpIxBadRequestCode int = 400

/*GetDirectV1SahamDpIxBadRequest Bad Request

swagger:response getDirectV1SahamDpIxBadRequest
*/
type GetDirectV1SahamDpIxBadRequest struct {
}

// NewGetDirectV1SahamDpIxBadRequest creates GetDirectV1SahamDpIxBadRequest with default headers values
func NewGetDirectV1SahamDpIxBadRequest() *GetDirectV1SahamDpIxBadRequest {

	return &GetDirectV1SahamDpIxBadRequest{}
}

// WriteResponse to the client
func (o *GetDirectV1SahamDpIxBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetDirectV1SahamDpIxNotFoundCode is the HTTP code returned for type GetDirectV1SahamDpIxNotFound
const GetDirectV1SahamDpIxNotFoundCode int = 404

/*GetDirectV1SahamDpIxNotFound Not Found

swagger:response getDirectV1SahamDpIxNotFound
*/
type GetDirectV1SahamDpIxNotFound struct {
}

// NewGetDirectV1SahamDpIxNotFound creates GetDirectV1SahamDpIxNotFound with default headers values
func NewGetDirectV1SahamDpIxNotFound() *GetDirectV1SahamDpIxNotFound {

	return &GetDirectV1SahamDpIxNotFound{}
}

// WriteResponse to the client
func (o *GetDirectV1SahamDpIxNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetDirectV1SahamDpIxInternalServerErrorCode is the HTTP code returned for type GetDirectV1SahamDpIxInternalServerError
const GetDirectV1SahamDpIxInternalServerErrorCode int = 500

/*GetDirectV1SahamDpIxInternalServerError Internal Server Error

swagger:response getDirectV1SahamDpIxInternalServerError
*/
type GetDirectV1SahamDpIxInternalServerError struct {
}

// NewGetDirectV1SahamDpIxInternalServerError creates GetDirectV1SahamDpIxInternalServerError with default headers values
func NewGetDirectV1SahamDpIxInternalServerError() *GetDirectV1SahamDpIxInternalServerError {

	return &GetDirectV1SahamDpIxInternalServerError{}
}

// WriteResponse to the client
func (o *GetDirectV1SahamDpIxInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
