// Code generated by go-swagger; DO NOT EDIT.

package index_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetDirectV1SahamDpIxHandlerFunc turns a function with the right signature into a get direct v1 saham dp ix handler
type GetDirectV1SahamDpIxHandlerFunc func(GetDirectV1SahamDpIxParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDirectV1SahamDpIxHandlerFunc) Handle(params GetDirectV1SahamDpIxParams) middleware.Responder {
	return fn(params)
}

// GetDirectV1SahamDpIxHandler interface for that can handle valid get direct v1 saham dp ix params
type GetDirectV1SahamDpIxHandler interface {
	Handle(GetDirectV1SahamDpIxParams) middleware.Responder
}

// NewGetDirectV1SahamDpIx creates a new http.Handler for the get direct v1 saham dp ix operation
func NewGetDirectV1SahamDpIx(ctx *middleware.Context, handler GetDirectV1SahamDpIxHandler) *GetDirectV1SahamDpIx {
	return &GetDirectV1SahamDpIx{Context: ctx, Handler: handler}
}

/* GetDirectV1SahamDpIx swagger:route GET /direct/v1/saham/dp/ix/ Index Data getDirectV1SahamDpIx

Get Index Data

Get Rasio Keuangan Data based on provided parameters.

*/
type GetDirectV1SahamDpIx struct {
	Context *middleware.Context
	Handler GetDirectV1SahamDpIxHandler
}

func (o *GetDirectV1SahamDpIx) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetDirectV1SahamDpIxParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
