// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"directApi/restapi/operations/balance_sheet_data"
	"directApi/restapi/operations/data_history"
	"directApi/restapi/operations/income_statement"
	"directApi/restapi/operations/index_data"
	"directApi/restapi/operations/informasi_pasar"
	"directApi/restapi/operations/rasio_keuangan"
)

// NewRasioKeuanganAPIAPI creates a new RasioKeuanganAPI instance
func NewRasioKeuanganAPIAPI(spec *loads.Document) *RasioKeuanganAPIAPI {
	return &RasioKeuanganAPIAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		DataHistoryGetDirectV1SahamDpEqHandler: data_history.GetDirectV1SahamDpEqHandlerFunc(func(params data_history.GetDirectV1SahamDpEqParams) middleware.Responder {
			return middleware.NotImplemented("operation data_history.GetDirectV1SahamDpEq has not yet been implemented")
		}),
		IndexDataGetDirectV1SahamDpIxHandler: index_data.GetDirectV1SahamDpIxHandlerFunc(func(params index_data.GetDirectV1SahamDpIxParams) middleware.Responder {
			return middleware.NotImplemented("operation index_data.GetDirectV1SahamDpIx has not yet been implemented")
		}),
		InformasiPasarGetDirectV1SahamFdrIPGetInformasiPasarDataHandler: informasi_pasar.GetDirectV1SahamFdrIPGetInformasiPasarDataHandlerFunc(func(params informasi_pasar.GetDirectV1SahamFdrIPGetInformasiPasarDataParams) middleware.Responder {
			return middleware.NotImplemented("operation informasi_pasar.GetDirectV1SahamFdrIPGetInformasiPasarData has not yet been implemented")
		}),
		RasioKeuanganGetDirectV1SahamFdrRkGetRasioKeuanganDataHandler: rasio_keuangan.GetDirectV1SahamFdrRkGetRasioKeuanganDataHandlerFunc(func(params rasio_keuangan.GetDirectV1SahamFdrRkGetRasioKeuanganDataParams) middleware.Responder {
			return middleware.NotImplemented("operation rasio_keuangan.GetDirectV1SahamFdrRkGetRasioKeuanganData has not yet been implemented")
		}),
		BalanceSheetDataGetDirectV1SahamLkBsHandler: balance_sheet_data.GetDirectV1SahamLkBsHandlerFunc(func(params balance_sheet_data.GetDirectV1SahamLkBsParams) middleware.Responder {
			return middleware.NotImplemented("operation balance_sheet_data.GetDirectV1SahamLkBs has not yet been implemented")
		}),
		IncomeStatementGetDirectV1SahamLkIsHandler: income_statement.GetDirectV1SahamLkIsHandlerFunc(func(params income_statement.GetDirectV1SahamLkIsParams) middleware.Responder {
			return middleware.NotImplemented("operation income_statement.GetDirectV1SahamLkIs has not yet been implemented")
		}),
	}
}

/*RasioKeuanganAPIAPI This file is auto-generated using go-swagger annotations. */
type RasioKeuanganAPIAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// DataHistoryGetDirectV1SahamDpEqHandler sets the operation handler for the get direct v1 saham dp eq operation
	DataHistoryGetDirectV1SahamDpEqHandler data_history.GetDirectV1SahamDpEqHandler
	// IndexDataGetDirectV1SahamDpIxHandler sets the operation handler for the get direct v1 saham dp ix operation
	IndexDataGetDirectV1SahamDpIxHandler index_data.GetDirectV1SahamDpIxHandler
	// InformasiPasarGetDirectV1SahamFdrIPGetInformasiPasarDataHandler sets the operation handler for the get direct v1 saham fdr IP get informasi pasar data operation
	InformasiPasarGetDirectV1SahamFdrIPGetInformasiPasarDataHandler informasi_pasar.GetDirectV1SahamFdrIPGetInformasiPasarDataHandler
	// RasioKeuanganGetDirectV1SahamFdrRkGetRasioKeuanganDataHandler sets the operation handler for the get direct v1 saham fdr rk get rasio keuangan data operation
	RasioKeuanganGetDirectV1SahamFdrRkGetRasioKeuanganDataHandler rasio_keuangan.GetDirectV1SahamFdrRkGetRasioKeuanganDataHandler
	// BalanceSheetDataGetDirectV1SahamLkBsHandler sets the operation handler for the get direct v1 saham lk bs operation
	BalanceSheetDataGetDirectV1SahamLkBsHandler balance_sheet_data.GetDirectV1SahamLkBsHandler
	// IncomeStatementGetDirectV1SahamLkIsHandler sets the operation handler for the get direct v1 saham lk is operation
	IncomeStatementGetDirectV1SahamLkIsHandler income_statement.GetDirectV1SahamLkIsHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *RasioKeuanganAPIAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *RasioKeuanganAPIAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *RasioKeuanganAPIAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *RasioKeuanganAPIAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *RasioKeuanganAPIAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *RasioKeuanganAPIAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *RasioKeuanganAPIAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *RasioKeuanganAPIAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *RasioKeuanganAPIAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the RasioKeuanganAPIAPI
func (o *RasioKeuanganAPIAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.DataHistoryGetDirectV1SahamDpEqHandler == nil {
		unregistered = append(unregistered, "data_history.GetDirectV1SahamDpEqHandler")
	}
	if o.IndexDataGetDirectV1SahamDpIxHandler == nil {
		unregistered = append(unregistered, "index_data.GetDirectV1SahamDpIxHandler")
	}
	if o.InformasiPasarGetDirectV1SahamFdrIPGetInformasiPasarDataHandler == nil {
		unregistered = append(unregistered, "informasi_pasar.GetDirectV1SahamFdrIPGetInformasiPasarDataHandler")
	}
	if o.RasioKeuanganGetDirectV1SahamFdrRkGetRasioKeuanganDataHandler == nil {
		unregistered = append(unregistered, "rasio_keuangan.GetDirectV1SahamFdrRkGetRasioKeuanganDataHandler")
	}
	if o.BalanceSheetDataGetDirectV1SahamLkBsHandler == nil {
		unregistered = append(unregistered, "balance_sheet_data.GetDirectV1SahamLkBsHandler")
	}
	if o.IncomeStatementGetDirectV1SahamLkIsHandler == nil {
		unregistered = append(unregistered, "income_statement.GetDirectV1SahamLkIsHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *RasioKeuanganAPIAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *RasioKeuanganAPIAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *RasioKeuanganAPIAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *RasioKeuanganAPIAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *RasioKeuanganAPIAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *RasioKeuanganAPIAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the rasio keuangan API API
func (o *RasioKeuanganAPIAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *RasioKeuanganAPIAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/direct/v1/saham/dp/eq"] = data_history.NewGetDirectV1SahamDpEq(o.context, o.DataHistoryGetDirectV1SahamDpEqHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/direct/v1/saham/dp/ix"] = index_data.NewGetDirectV1SahamDpIx(o.context, o.IndexDataGetDirectV1SahamDpIxHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/direct/v1/saham/fdr/ip/get-informasi-pasar-data"] = informasi_pasar.NewGetDirectV1SahamFdrIPGetInformasiPasarData(o.context, o.InformasiPasarGetDirectV1SahamFdrIPGetInformasiPasarDataHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/direct/v1/saham/fdr/rk/get-rasio-keuangan-data"] = rasio_keuangan.NewGetDirectV1SahamFdrRkGetRasioKeuanganData(o.context, o.RasioKeuanganGetDirectV1SahamFdrRkGetRasioKeuanganDataHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/direct/v1/saham/lk/bs"] = balance_sheet_data.NewGetDirectV1SahamLkBs(o.context, o.BalanceSheetDataGetDirectV1SahamLkBsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/direct/v1/saham/lk/is"] = income_statement.NewGetDirectV1SahamLkIs(o.context, o.IncomeStatementGetDirectV1SahamLkIsHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *RasioKeuanganAPIAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *RasioKeuanganAPIAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *RasioKeuanganAPIAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *RasioKeuanganAPIAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *RasioKeuanganAPIAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[um][path] = builder(h)
	}
}
