// Code generated by go-swagger; DO NOT EDIT.

package informasi_pasar

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
)

// GetDirectV1SahamFdrIPGetInformasiPasarDataURL generates an URL for the get direct v1 saham fdr IP get informasi pasar data operation
type GetDirectV1SahamFdrIPGetInformasiPasarDataURL struct {
	Granularity *string
	Periode     *string
	Q           *string
	SecCode     string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetDirectV1SahamFdrIPGetInformasiPasarDataURL) WithBasePath(bp string) *GetDirectV1SahamFdrIPGetInformasiPasarDataURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetDirectV1SahamFdrIPGetInformasiPasarDataURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetDirectV1SahamFdrIPGetInformasiPasarDataURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/direct/v1/saham/fdr/ip/get-informasi-pasar-data"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var granularityQ string
	if o.Granularity != nil {
		granularityQ = *o.Granularity
	}
	if granularityQ != "" {
		qs.Set("granularity", granularityQ)
	}

	var periodeQ string
	if o.Periode != nil {
		periodeQ = *o.Periode
	}
	if periodeQ != "" {
		qs.Set("periode", periodeQ)
	}

	var qQ string
	if o.Q != nil {
		qQ = *o.Q
	}
	if qQ != "" {
		qs.Set("q", qQ)
	}

	secCodeQ := o.SecCode
	if secCodeQ != "" {
		qs.Set("secCode", secCodeQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetDirectV1SahamFdrIPGetInformasiPasarDataURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetDirectV1SahamFdrIPGetInformasiPasarDataURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetDirectV1SahamFdrIPGetInformasiPasarDataURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetDirectV1SahamFdrIPGetInformasiPasarDataURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetDirectV1SahamFdrIPGetInformasiPasarDataURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetDirectV1SahamFdrIPGetInformasiPasarDataURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
