// Code generated by go-swagger; DO NOT EDIT.

package informasi_pasar

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"directApi/models"
)

// GetDirectV1SahamFdrIPGetInformasiPasarDataOKCode is the HTTP code returned for type GetDirectV1SahamFdrIPGetInformasiPasarDataOK
const GetDirectV1SahamFdrIPGetInformasiPasarDataOKCode int = 200

/*GetDirectV1SahamFdrIPGetInformasiPasarDataOK Successful response

swagger:response getDirectV1SahamFdrIpGetInformasiPasarDataOK
*/
type GetDirectV1SahamFdrIPGetInformasiPasarDataOK struct {

	/*
	  In: Body
	*/
	Payload []*models.ResultIndexDataIinfPasar `json:"body,omitempty"`
}

// NewGetDirectV1SahamFdrIPGetInformasiPasarDataOK creates GetDirectV1SahamFdrIPGetInformasiPasarDataOK with default headers values
func NewGetDirectV1SahamFdrIPGetInformasiPasarDataOK() *GetDirectV1SahamFdrIPGetInformasiPasarDataOK {

	return &GetDirectV1SahamFdrIPGetInformasiPasarDataOK{}
}

// WithPayload adds the payload to the get direct v1 saham fdr Ip get informasi pasar data o k response
func (o *GetDirectV1SahamFdrIPGetInformasiPasarDataOK) WithPayload(payload []*models.ResultIndexDataIinfPasar) *GetDirectV1SahamFdrIPGetInformasiPasarDataOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get direct v1 saham fdr Ip get informasi pasar data o k response
func (o *GetDirectV1SahamFdrIPGetInformasiPasarDataOK) SetPayload(payload []*models.ResultIndexDataIinfPasar) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDirectV1SahamFdrIPGetInformasiPasarDataOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.ResultIndexDataIinfPasar, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetDirectV1SahamFdrIPGetInformasiPasarDataBadRequestCode is the HTTP code returned for type GetDirectV1SahamFdrIPGetInformasiPasarDataBadRequest
const GetDirectV1SahamFdrIPGetInformasiPasarDataBadRequestCode int = 400

/*GetDirectV1SahamFdrIPGetInformasiPasarDataBadRequest Error response

swagger:response getDirectV1SahamFdrIpGetInformasiPasarDataBadRequest
*/
type GetDirectV1SahamFdrIPGetInformasiPasarDataBadRequest struct {

	/*
	  In: Body
	*/
	Payload *GetDirectV1SahamFdrIPGetInformasiPasarDataBadRequestBody `json:"body,omitempty"`
}

// NewGetDirectV1SahamFdrIPGetInformasiPasarDataBadRequest creates GetDirectV1SahamFdrIPGetInformasiPasarDataBadRequest with default headers values
func NewGetDirectV1SahamFdrIPGetInformasiPasarDataBadRequest() *GetDirectV1SahamFdrIPGetInformasiPasarDataBadRequest {

	return &GetDirectV1SahamFdrIPGetInformasiPasarDataBadRequest{}
}

// WithPayload adds the payload to the get direct v1 saham fdr Ip get informasi pasar data bad request response
func (o *GetDirectV1SahamFdrIPGetInformasiPasarDataBadRequest) WithPayload(payload *GetDirectV1SahamFdrIPGetInformasiPasarDataBadRequestBody) *GetDirectV1SahamFdrIPGetInformasiPasarDataBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get direct v1 saham fdr Ip get informasi pasar data bad request response
func (o *GetDirectV1SahamFdrIPGetInformasiPasarDataBadRequest) SetPayload(payload *GetDirectV1SahamFdrIPGetInformasiPasarDataBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDirectV1SahamFdrIPGetInformasiPasarDataBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
