// Code generated by go-swagger; DO NOT EDIT.

package informasi_pasar

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetDirectV1SahamFdrIPGetInformasiPasarDataHandlerFunc turns a function with the right signature into a get direct v1 saham fdr IP get informasi pasar data handler
type GetDirectV1SahamFdrIPGetInformasiPasarDataHandlerFunc func(GetDirectV1SahamFdrIPGetInformasiPasarDataParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDirectV1SahamFdrIPGetInformasiPasarDataHandlerFunc) Handle(params GetDirectV1SahamFdrIPGetInformasiPasarDataParams) middleware.Responder {
	return fn(params)
}

// GetDirectV1SahamFdrIPGetInformasiPasarDataHandler interface for that can handle valid get direct v1 saham fdr IP get informasi pasar data params
type GetDirectV1SahamFdrIPGetInformasiPasarDataHandler interface {
	Handle(GetDirectV1SahamFdrIPGetInformasiPasarDataParams) middleware.Responder
}

// NewGetDirectV1SahamFdrIPGetInformasiPasarData creates a new http.Handler for the get direct v1 saham fdr IP get informasi pasar data operation
func NewGetDirectV1SahamFdrIPGetInformasiPasarData(ctx *middleware.Context, handler GetDirectV1SahamFdrIPGetInformasiPasarDataHandler) *GetDirectV1SahamFdrIPGetInformasiPasarData {
	return &GetDirectV1SahamFdrIPGetInformasiPasarData{Context: ctx, Handler: handler}
}

/* GetDirectV1SahamFdrIPGetInformasiPasarData swagger:route GET /direct/v1/saham/fdr/ip/get-informasi-pasar-data Informasi Pasar getDirectV1SahamFdrIpGetInformasiPasarData

Get Informasi Pasar Data

Get Informasi Pasar Data based on provided parameters.

*/
type GetDirectV1SahamFdrIPGetInformasiPasarData struct {
	Context *middleware.Context
	Handler GetDirectV1SahamFdrIPGetInformasiPasarDataHandler
}

func (o *GetDirectV1SahamFdrIPGetInformasiPasarData) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetDirectV1SahamFdrIPGetInformasiPasarDataParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetDirectV1SahamFdrIPGetInformasiPasarDataBadRequestBody get direct v1 saham fdr IP get informasi pasar data bad request body
//
// swagger:model GetDirectV1SahamFdrIPGetInformasiPasarDataBadRequestBody
type GetDirectV1SahamFdrIPGetInformasiPasarDataBadRequestBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this get direct v1 saham fdr IP get informasi pasar data bad request body
func (o *GetDirectV1SahamFdrIPGetInformasiPasarDataBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get direct v1 saham fdr IP get informasi pasar data bad request body based on context it is used
func (o *GetDirectV1SahamFdrIPGetInformasiPasarDataBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetDirectV1SahamFdrIPGetInformasiPasarDataBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetDirectV1SahamFdrIPGetInformasiPasarDataBadRequestBody) UnmarshalBinary(b []byte) error {
	var res GetDirectV1SahamFdrIPGetInformasiPasarDataBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
