// Code generated by go-swagger; DO NOT EDIT.

package rasio_keuangan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"directApi/models"
)

// GetDirectV1SahamFdrRkGetRasioKeuanganDataOKCode is the HTTP code returned for type GetDirectV1SahamFdrRkGetRasioKeuanganDataOK
const GetDirectV1SahamFdrRkGetRasioKeuanganDataOKCode int = 200

/*GetDirectV1SahamFdrRkGetRasioKeuanganDataOK Successful response

swagger:response getDirectV1SahamFdrRkGetRasioKeuanganDataOK
*/
type GetDirectV1SahamFdrRkGetRasioKeuanganDataOK struct {

	/*
	  In: Body
	*/
	Payload []*models.ResultIndexData `json:"body,omitempty"`
}

// NewGetDirectV1SahamFdrRkGetRasioKeuanganDataOK creates GetDirectV1SahamFdrRkGetRasioKeuanganDataOK with default headers values
func NewGetDirectV1SahamFdrRkGetRasioKeuanganDataOK() *GetDirectV1SahamFdrRkGetRasioKeuanganDataOK {

	return &GetDirectV1SahamFdrRkGetRasioKeuanganDataOK{}
}

// WithPayload adds the payload to the get direct v1 saham fdr rk get rasio keuangan data o k response
func (o *GetDirectV1SahamFdrRkGetRasioKeuanganDataOK) WithPayload(payload []*models.ResultIndexData) *GetDirectV1SahamFdrRkGetRasioKeuanganDataOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get direct v1 saham fdr rk get rasio keuangan data o k response
func (o *GetDirectV1SahamFdrRkGetRasioKeuanganDataOK) SetPayload(payload []*models.ResultIndexData) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDirectV1SahamFdrRkGetRasioKeuanganDataOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.ResultIndexData, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetDirectV1SahamFdrRkGetRasioKeuanganDataBadRequestCode is the HTTP code returned for type GetDirectV1SahamFdrRkGetRasioKeuanganDataBadRequest
const GetDirectV1SahamFdrRkGetRasioKeuanganDataBadRequestCode int = 400

/*GetDirectV1SahamFdrRkGetRasioKeuanganDataBadRequest Error response

swagger:response getDirectV1SahamFdrRkGetRasioKeuanganDataBadRequest
*/
type GetDirectV1SahamFdrRkGetRasioKeuanganDataBadRequest struct {

	/*
	  In: Body
	*/
	Payload *GetDirectV1SahamFdrRkGetRasioKeuanganDataBadRequestBody `json:"body,omitempty"`
}

// NewGetDirectV1SahamFdrRkGetRasioKeuanganDataBadRequest creates GetDirectV1SahamFdrRkGetRasioKeuanganDataBadRequest with default headers values
func NewGetDirectV1SahamFdrRkGetRasioKeuanganDataBadRequest() *GetDirectV1SahamFdrRkGetRasioKeuanganDataBadRequest {

	return &GetDirectV1SahamFdrRkGetRasioKeuanganDataBadRequest{}
}

// WithPayload adds the payload to the get direct v1 saham fdr rk get rasio keuangan data bad request response
func (o *GetDirectV1SahamFdrRkGetRasioKeuanganDataBadRequest) WithPayload(payload *GetDirectV1SahamFdrRkGetRasioKeuanganDataBadRequestBody) *GetDirectV1SahamFdrRkGetRasioKeuanganDataBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get direct v1 saham fdr rk get rasio keuangan data bad request response
func (o *GetDirectV1SahamFdrRkGetRasioKeuanganDataBadRequest) SetPayload(payload *GetDirectV1SahamFdrRkGetRasioKeuanganDataBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDirectV1SahamFdrRkGetRasioKeuanganDataBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
