// Code generated by go-swagger; DO NOT EDIT.

package data_history

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
)

// GetDirectV1SahamDpEqURL generates an URL for the get direct v1 saham dp eq operation
type GetDirectV1SahamDpEqURL struct {
	EndDate     string
	Granularity string
	SecCode     string
	StartDate   string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetDirectV1SahamDpEqURL) WithBasePath(bp string) *GetDirectV1SahamDpEqURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetDirectV1SahamDpEqURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetDirectV1SahamDpEqURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/direct/v1/saham/dp/eq/"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	endDateQ := o.EndDate
	if endDateQ != "" {
		qs.Set("endDate", endDateQ)
	}

	granularityQ := o.Granularity
	if granularityQ != "" {
		qs.Set("granularity", granularityQ)
	}

	secCodeQ := o.SecCode
	if secCodeQ != "" {
		qs.Set("secCode", secCodeQ)
	}

	startDateQ := o.StartDate
	if startDateQ != "" {
		qs.Set("startDate", startDateQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetDirectV1SahamDpEqURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetDirectV1SahamDpEqURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetDirectV1SahamDpEqURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetDirectV1SahamDpEqURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetDirectV1SahamDpEqURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetDirectV1SahamDpEqURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
