// Code generated by go-swagger; DO NOT EDIT.

package data_history

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetDirectV1SahamDpEqParams creates a new GetDirectV1SahamDpEqParams object
//
// There are no default values defined in the spec.
func NewGetDirectV1SahamDpEqParams() GetDirectV1SahamDpEqParams {

	return GetDirectV1SahamDpEqParams{}
}

// GetDirectV1SahamDpEqParams contains all the bound params for the get direct v1 saham dp eq operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetDirectV1SahamDpEq
type GetDirectV1SahamDpEqParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: query
	*/
	EndDate string
	/*
	  Required: true
	  In: query
	*/
	Granularity string
	/*
	  Required: true
	  In: query
	*/
	SecCode string
	/*
	  Required: true
	  In: query
	*/
	StartDate string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetDirectV1SahamDpEqParams() beforehand.
func (o *GetDirectV1SahamDpEqParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qEndDate, qhkEndDate, _ := qs.GetOK("endDate")
	if err := o.bindEndDate(qEndDate, qhkEndDate, route.Formats); err != nil {
		res = append(res, err)
	}

	qGranularity, qhkGranularity, _ := qs.GetOK("granularity")
	if err := o.bindGranularity(qGranularity, qhkGranularity, route.Formats); err != nil {
		res = append(res, err)
	}

	qSecCode, qhkSecCode, _ := qs.GetOK("secCode")
	if err := o.bindSecCode(qSecCode, qhkSecCode, route.Formats); err != nil {
		res = append(res, err)
	}

	qStartDate, qhkStartDate, _ := qs.GetOK("startDate")
	if err := o.bindStartDate(qStartDate, qhkStartDate, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindEndDate binds and validates parameter EndDate from query.
func (o *GetDirectV1SahamDpEqParams) bindEndDate(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("endDate", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("endDate", "query", raw); err != nil {
		return err
	}
	o.EndDate = raw

	return nil
}

// bindGranularity binds and validates parameter Granularity from query.
func (o *GetDirectV1SahamDpEqParams) bindGranularity(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("granularity", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("granularity", "query", raw); err != nil {
		return err
	}
	o.Granularity = raw

	return nil
}

// bindSecCode binds and validates parameter SecCode from query.
func (o *GetDirectV1SahamDpEqParams) bindSecCode(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("secCode", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("secCode", "query", raw); err != nil {
		return err
	}
	o.SecCode = raw

	return nil
}

// bindStartDate binds and validates parameter StartDate from query.
func (o *GetDirectV1SahamDpEqParams) bindStartDate(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("startDate", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("startDate", "query", raw); err != nil {
		return err
	}
	o.StartDate = raw

	return nil
}
