// Code generated by go-swagger; DO NOT EDIT.

package data_history

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetDirectV1SahamDpEqOKCode is the HTTP code returned for type GetDirectV1SahamDpEqOK
const GetDirectV1SahamDpEqOKCode int = 200

/*GetDirectV1SahamDpEqOK Successful response

swagger:response getDirectV1SahamDpEqOK
*/
type GetDirectV1SahamDpEqOK struct {

	/*
	  In: Body
	*/
	Payload *GetDirectV1SahamDpEqOKBody `json:"body,omitempty"`
}

// NewGetDirectV1SahamDpEqOK creates GetDirectV1SahamDpEqOK with default headers values
func NewGetDirectV1SahamDpEqOK() *GetDirectV1SahamDpEqOK {

	return &GetDirectV1SahamDpEqOK{}
}

// WithPayload adds the payload to the get direct v1 saham dp eq o k response
func (o *GetDirectV1SahamDpEqOK) WithPayload(payload *GetDirectV1SahamDpEqOKBody) *GetDirectV1SahamDpEqOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get direct v1 saham dp eq o k response
func (o *GetDirectV1SahamDpEqOK) SetPayload(payload *GetDirectV1SahamDpEqOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDirectV1SahamDpEqOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDirectV1SahamDpEqBadRequestCode is the HTTP code returned for type GetDirectV1SahamDpEqBadRequest
const GetDirectV1SahamDpEqBadRequestCode int = 400

/*GetDirectV1SahamDpEqBadRequest Bad Request

swagger:response getDirectV1SahamDpEqBadRequest
*/
type GetDirectV1SahamDpEqBadRequest struct {
}

// NewGetDirectV1SahamDpEqBadRequest creates GetDirectV1SahamDpEqBadRequest with default headers values
func NewGetDirectV1SahamDpEqBadRequest() *GetDirectV1SahamDpEqBadRequest {

	return &GetDirectV1SahamDpEqBadRequest{}
}

// WriteResponse to the client
func (o *GetDirectV1SahamDpEqBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetDirectV1SahamDpEqNotFoundCode is the HTTP code returned for type GetDirectV1SahamDpEqNotFound
const GetDirectV1SahamDpEqNotFoundCode int = 404

/*GetDirectV1SahamDpEqNotFound Not Found

swagger:response getDirectV1SahamDpEqNotFound
*/
type GetDirectV1SahamDpEqNotFound struct {
}

// NewGetDirectV1SahamDpEqNotFound creates GetDirectV1SahamDpEqNotFound with default headers values
func NewGetDirectV1SahamDpEqNotFound() *GetDirectV1SahamDpEqNotFound {

	return &GetDirectV1SahamDpEqNotFound{}
}

// WriteResponse to the client
func (o *GetDirectV1SahamDpEqNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetDirectV1SahamDpEqMethodNotAllowedCode is the HTTP code returned for type GetDirectV1SahamDpEqMethodNotAllowed
const GetDirectV1SahamDpEqMethodNotAllowedCode int = 405

/*GetDirectV1SahamDpEqMethodNotAllowed Method Not Allowed

swagger:response getDirectV1SahamDpEqMethodNotAllowed
*/
type GetDirectV1SahamDpEqMethodNotAllowed struct {
}

// NewGetDirectV1SahamDpEqMethodNotAllowed creates GetDirectV1SahamDpEqMethodNotAllowed with default headers values
func NewGetDirectV1SahamDpEqMethodNotAllowed() *GetDirectV1SahamDpEqMethodNotAllowed {

	return &GetDirectV1SahamDpEqMethodNotAllowed{}
}

// WriteResponse to the client
func (o *GetDirectV1SahamDpEqMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// GetDirectV1SahamDpEqInternalServerErrorCode is the HTTP code returned for type GetDirectV1SahamDpEqInternalServerError
const GetDirectV1SahamDpEqInternalServerErrorCode int = 500

/*GetDirectV1SahamDpEqInternalServerError Internal Server Error

swagger:response getDirectV1SahamDpEqInternalServerError
*/
type GetDirectV1SahamDpEqInternalServerError struct {
}

// NewGetDirectV1SahamDpEqInternalServerError creates GetDirectV1SahamDpEqInternalServerError with default headers values
func NewGetDirectV1SahamDpEqInternalServerError() *GetDirectV1SahamDpEqInternalServerError {

	return &GetDirectV1SahamDpEqInternalServerError{}
}

// WriteResponse to the client
func (o *GetDirectV1SahamDpEqInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
