// Code generated by go-swagger; DO NOT EDIT.

package income_statement

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetDirectV1SahamLkIsOKCode is the HTTP code returned for type GetDirectV1SahamLkIsOK
const GetDirectV1SahamLkIsOKCode int = 200

/*GetDirectV1SahamLkIsOK Successful response

swagger:response getDirectV1SahamLkIsOK
*/
type GetDirectV1SahamLkIsOK struct {

	/*
	  In: Body
	*/
	Payload []interface{} `json:"body,omitempty"`
}

// NewGetDirectV1SahamLkIsOK creates GetDirectV1SahamLkIsOK with default headers values
func NewGetDirectV1SahamLkIsOK() *GetDirectV1SahamLkIsOK {

	return &GetDirectV1SahamLkIsOK{}
}

// WithPayload adds the payload to the get direct v1 saham lk is o k response
func (o *GetDirectV1SahamLkIsOK) WithPayload(payload []interface{}) *GetDirectV1SahamLkIsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get direct v1 saham lk is o k response
func (o *GetDirectV1SahamLkIsOK) SetPayload(payload []interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDirectV1SahamLkIsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]interface{}, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetDirectV1SahamLkIsInternalServerErrorCode is the HTTP code returned for type GetDirectV1SahamLkIsInternalServerError
const GetDirectV1SahamLkIsInternalServerErrorCode int = 500

/*GetDirectV1SahamLkIsInternalServerError Internal server error

swagger:response getDirectV1SahamLkIsInternalServerError
*/
type GetDirectV1SahamLkIsInternalServerError struct {
}

// NewGetDirectV1SahamLkIsInternalServerError creates GetDirectV1SahamLkIsInternalServerError with default headers values
func NewGetDirectV1SahamLkIsInternalServerError() *GetDirectV1SahamLkIsInternalServerError {

	return &GetDirectV1SahamLkIsInternalServerError{}
}

// WriteResponse to the client
func (o *GetDirectV1SahamLkIsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
