// Code generated by go-swagger; DO NOT EDIT.

package balance_sheet_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetDirectV1SahamLkBsHandlerFunc turns a function with the right signature into a get direct v1 saham lk bs handler
type GetDirectV1SahamLkBsHandlerFunc func(GetDirectV1SahamLkBsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDirectV1SahamLkBsHandlerFunc) Handle(params GetDirectV1SahamLkBsParams) middleware.Responder {
	return fn(params)
}

// GetDirectV1SahamLkBsHandler interface for that can handle valid get direct v1 saham lk bs params
type GetDirectV1SahamLkBsHandler interface {
	Handle(GetDirectV1SahamLkBsParams) middleware.Responder
}

// NewGetDirectV1SahamLkBs creates a new http.Handler for the get direct v1 saham lk bs operation
func NewGetDirectV1SahamLkBs(ctx *middleware.Context, handler GetDirectV1SahamLkBsHandler) *GetDirectV1SahamLkBs {
	return &GetDirectV1SahamLkBs{Context: ctx, Handler: handler}
}

/* GetDirectV1SahamLkBs swagger:route GET /direct/v1/saham/lk/bs/ Balance Sheet Data getDirectV1SahamLkBs

Get Balance Sheet Data

Get Rasio Keuangan Data based on provided parameters.

*/
type GetDirectV1SahamLkBs struct {
	Context *middleware.Context
	Handler GetDirectV1SahamLkBsHandler
}

func (o *GetDirectV1SahamLkBs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetDirectV1SahamLkBsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
