// Code generated by go-swagger; DO NOT EDIT.

package balance_sheet_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetDirectV1SahamLkBsOKCode is the HTTP code returned for type GetDirectV1SahamLkBsOK
const GetDirectV1SahamLkBsOKCode int = 200

/*GetDirectV1SahamLkBsOK Successful response

swagger:response getDirectV1SahamLkBsOK
*/
type GetDirectV1SahamLkBsOK struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewGetDirectV1SahamLkBsOK creates GetDirectV1SahamLkBsOK with default headers values
func NewGetDirectV1SahamLkBsOK() *GetDirectV1SahamLkBsOK {

	return &GetDirectV1SahamLkBsOK{}
}

// WithPayload adds the payload to the get direct v1 saham lk bs o k response
func (o *GetDirectV1SahamLkBsOK) WithPayload(payload interface{}) *GetDirectV1SahamLkBsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get direct v1 saham lk bs o k response
func (o *GetDirectV1SahamLkBsOK) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDirectV1SahamLkBsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetDirectV1SahamLkBsBadRequestCode is the HTTP code returned for type GetDirectV1SahamLkBsBadRequest
const GetDirectV1SahamLkBsBadRequestCode int = 400

/*GetDirectV1SahamLkBsBadRequest Bad Request

swagger:response getDirectV1SahamLkBsBadRequest
*/
type GetDirectV1SahamLkBsBadRequest struct {
}

// NewGetDirectV1SahamLkBsBadRequest creates GetDirectV1SahamLkBsBadRequest with default headers values
func NewGetDirectV1SahamLkBsBadRequest() *GetDirectV1SahamLkBsBadRequest {

	return &GetDirectV1SahamLkBsBadRequest{}
}

// WriteResponse to the client
func (o *GetDirectV1SahamLkBsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetDirectV1SahamLkBsNotFoundCode is the HTTP code returned for type GetDirectV1SahamLkBsNotFound
const GetDirectV1SahamLkBsNotFoundCode int = 404

/*GetDirectV1SahamLkBsNotFound Not Found

swagger:response getDirectV1SahamLkBsNotFound
*/
type GetDirectV1SahamLkBsNotFound struct {
}

// NewGetDirectV1SahamLkBsNotFound creates GetDirectV1SahamLkBsNotFound with default headers values
func NewGetDirectV1SahamLkBsNotFound() *GetDirectV1SahamLkBsNotFound {

	return &GetDirectV1SahamLkBsNotFound{}
}

// WriteResponse to the client
func (o *GetDirectV1SahamLkBsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetDirectV1SahamLkBsInternalServerErrorCode is the HTTP code returned for type GetDirectV1SahamLkBsInternalServerError
const GetDirectV1SahamLkBsInternalServerErrorCode int = 500

/*GetDirectV1SahamLkBsInternalServerError Internal Server Error

swagger:response getDirectV1SahamLkBsInternalServerError
*/
type GetDirectV1SahamLkBsInternalServerError struct {
}

// NewGetDirectV1SahamLkBsInternalServerError creates GetDirectV1SahamLkBsInternalServerError with default headers values
func NewGetDirectV1SahamLkBsInternalServerError() *GetDirectV1SahamLkBsInternalServerError {

	return &GetDirectV1SahamLkBsInternalServerError{}
}

// WriteResponse to the client
func (o *GetDirectV1SahamLkBsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
